const crypto = require('crypto');
const admin = require('firebase-admin');
const REQUIREMENTS = { 6: 1, 12: 2, 24: 3, 30: 4 };
const DEVICE_RE = /^HWID-[A-Z0-9]{24}$/;
const HOSTNAME = String(process.env.TURNSTILE_HOSTNAME || 'zkeysystem.vercel.app').trim().toLowerCase();
function json(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(payload));}
function parseServiceAccount(raw){let s=String(raw||'').trim(),c=[s];if((s.startsWith('"')&&s.endsWith('"'))||(s.startsWith("'")&&s.endsWith("'"))){try{const q=s.startsWith('"')?JSON.parse(s):s.slice(1,-1);if(typeof q==='string')c.unshift(q)}catch{}}for(const x of c){try{let o=JSON.parse(x);if(typeof o==='string')o=JSON.parse(o);if(o&&o.project_id&&o.client_email&&o.private_key){o.private_key=String(o.private_key).replace(/\\n/g,'\n');return o}}catch{}}throw new Error('La credencial de Firebase no es válida.');}
function db(){if(admin.apps.length)return admin.app().database();const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSONZ||process.env.FIREBASE_SERVICE_ACCOUNT_JSON,url=process.env.FIREBASE_DATABASE_URL;if(!raw||!url)throw new Error('Firebase del servidor no está configurado.');return admin.initializeApp({credential:admin.credential.cert(parseServiceAccount(raw)),databaseURL:url}).database();}
function cookie(req,name){const raw=String(req.headers?.cookie||'');for(const p of raw.split(';')){const [k,...r]=p.trim().split('=');if(k===name)return r.join('=')}return '';}
function equal(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function sha256(value){return crypto.createHash('sha256').update(String(value||'')).digest('hex')}
function body(req){if(req.body&&typeof req.body==='object')return Promise.resolve(req.body);return new Promise((resolve,reject)=>{let r='';req.on('data',c=>{r+=c;if(r.length>12000)reject(new Error('Solicitud demasiado grande.'))});req.on('end',()=>{if(!r)return resolve({});try{resolve(JSON.parse(r))}catch{reject(new Error('JSON inválido.'))}});req.on('error',reject)})}
async function verifyHuman(token,req){const secret=String(process.env.TURNSTILE_SECRET_KEY||'').trim();if(!secret)throw Object.assign(new Error('TURNSTILE_SECRET_KEY no está configurada en Vercel.'),{status:500});if(!token||token.length>2048)throw Object.assign(new Error('Completa la verificación humana.'),{status:403});const remote=String(req.headers?.['cf-connecting-ip']||req.headers?.['x-forwarded-for']||'').split(',')[0].trim();const payload={secret,response:token,idempotency_key:crypto.randomUUID()};if(remote)payload.remoteip=remote;const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),7000);let r,d;try{r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload),signal:ac.signal,cache:'no-store'});d=await r.json()}finally{clearTimeout(tm)}if(!r.ok||!d?.success)throw Object.assign(new Error('La verificación humana fue rechazada. Completa Turnstile de nuevo.'),{status:403});if(String(d.action||'').trim()!=='keyverify')throw Object.assign(new Error('La verificación no corresponde a este acceso.'),{status:403});if(HOSTNAME&&String(d.hostname||'').trim().toLowerCase()!==HOSTNAME)throw Object.assign(new Error('Host de verificación inválido.'),{status:403});return d;}
async function recoverFromTicket(database,ticketHash,sessionId,deviceId,link,userAgentHash,acceptLanguageHash){if(!ticketHash)return null;const ref=database.ref(`sessionTickets/${ticketHash}`),snap=await ref.get();if(!snap.exists())return null;const t=snap.val()||{};if(t.used===true||Number(t.expiresAt||0)<=Date.now()){await ref.remove();return null;}if(String(t.sessionId||'')!==sessionId||String(t.deviceId||'')!==deviceId||Number(t.link)!==link)return null;if(t.userAgentHash&&!equal(String(t.userAgentHash),userAgentHash))return null;if(t.acceptLanguageHash&&!equal(String(t.acceptLanguageHash),acceptLanguageHash))return null;const required=REQUIREMENTS[Number(t.dur)];if(!required)return null;const session={id:sessionId,dur:Number(t.dur),link:Number(t.link),state:'awaiting_external_return',createdAt:Number(t.createdAt||Date.now()),expiresAt:Number(t.expiresAt),deviceId,completedLinks:Math.max(0,Number(t.completedLinks||0)),attempts:1,verificationUsed:false,ticketHash,ticketIssuedAt:Number(t.createdAt||Date.now()),ticketExpiresAt:Number(t.expiresAt),ticketUserAgentHash:String(t.userAgentHash||''),ticketAcceptLanguageHash:String(t.acceptLanguageHash||''),ticketProviderHost:String(t.providerHost||''),verificationNonce:crypto.randomBytes(24).toString('hex')};await database.ref(`sessions/${sessionId}`).set(session);return session;}
function sessionPayload(s){return {id:s.id,dur:Number(s.dur),link:Number(s.link),state:String(s.state||''),createdAt:Number(s.createdAt||0),expiresAt:Number(s.expiresAt||0)};}
module.exports=async(req,res)=>{try{if(req.method!=='POST')return json(res,405,{error:'Método no permitido.'});const x=await body(req),sessionId=String(x.sessionId||'').trim(),hash=String(x.hash||'').trim(),link=Number(x.link),deviceId=String(x.deviceId||'').trim(),turnstileToken=String(x.turnstileToken||'').trim();if(!/^[a-f0-9-]{20,100}$/i.test(sessionId))return json(res,400,{error:'Sesión inválida.'});if(!/^[A-Za-z0-9]{64}$/.test(hash))return json(res,400,{error:'Comprobante inválido.'});if(!Number.isInteger(link)||link<1||link>4)return json(res,400,{error:'Paso inválido.'});if(!DEVICE_RE.test(deviceId))return json(res,400,{error:'Device ID inválido.'});
const database=db(),ref=database.ref(`sessions/${sessionId}`),ticket=cookie(req,'__Host-znexus_ticket'),ticketHash=ticket?sha256(ticket):'',userAgentHash=sha256(req.headers?.['user-agent']||''),acceptLanguageHash=sha256(req.headers?.['accept-language']||'');let snap=await ref.get();if(!snap.exists()){const restored=await recoverFromTicket(database,ticketHash,sessionId,deviceId,link,userAgentHash,acceptLanguageHash);if(!restored)return json(res,404,{error:'Sesión no encontrada.'});snap={exists:()=>true,val:()=>restored};}
let s=snap.val()||{},required=REQUIREMENTS[Number(s.dur)];if(!required)return json(res,400,{error:'Duración de sesión inválida.'});if(link>required)return json(res,409,{error:'Ese paso no es necesario para esta duración.'});if(String(s.deviceId||'')!==deviceId)return json(res,403,{error:'El dispositivo no coincide con la sesión.'});if(Number(s.expiresAt||0)<=Date.now()){await ref.remove();return json(res,410,{error:'La sesión expiró.'});}
// Idempotency: repeated callbacks from the same browser/HWID are accepted.
if(s.state==='complete'&&Number(s.completedLinks||0)>=required){return json(res,200,{session:sessionPayload(s),alreadyProcessed:true});}
if(Number(s.completedLinks||0)>=link&&Number(s.link||0)>link){return json(res,200,{session:sessionPayload(s),alreadyProcessed:true});}
if(s.verificationUsed===true&&String(s.lastVerifiedHash||'')===hash&&String(s.lastVerifiedDeviceId||s.deviceId||'')===deviceId&&Number(s.link||0)>link){return json(res,200,{session:sessionPayload(s),alreadyProcessed:true});}
if(s.state!=='awaiting_external_return'||Number(s.link)!==link)return json(res,409,{error:'Ese paso no está pendiente.'});if(s.verificationUsed===true)return json(res,409,{error:'Este intento ya fue procesado.'});const currentTicketHash=s.ticketHash||ticketHash;if(!ticket||!currentTicketHash||!equal(ticketHash,currentTicketHash))return json(res,403,{error:'Pase de navegador inválido. Regresa usando el flujo normal.'});if(Number(s.ticketExpiresAt||0)<=Date.now())return json(res,403,{error:'El pase de navegador expiró. Inicia el paso de nuevo.'});if(s.ticketUserAgentHash&&!equal(String(s.ticketUserAgentHash),userAgentHash))return json(res,403,{error:'El navegador no coincide con el que inició este paso.'});if(s.ticketAcceptLanguageHash&&!equal(String(s.ticketAcceptLanguageHash),acceptLanguageHash))return json(res,403,{error:'La sesión de navegador no coincide.'});
const now=Date.now(),completed=Math.min(required,Number(s.completedLinks||0)+1),next=Number(s.link)<required?Number(s.link)+1:Number(s.link),state=completed>=required?'complete':'ready';if(completed===required)await verifyHuman(turnstileToken,req);
const tx=await ref.transaction(current=>{if(!current||typeof current!=='object')return;if(String(current.deviceId||'')!==deviceId)return;if(current.state==='complete'&&Number(current.completedLinks||0)>=required)return current;if(Number(current.completedLinks||0)>=link&&Number(current.link||0)>link)return current;if(current.state!=='awaiting_external_return'||Number(current.link)!==link)return;if(current.verificationUsed===true)return;if(!current.ticketHash||!equal(String(current.ticketHash),ticketHash))return;if(Number(current.ticketExpiresAt||0)<=Date.now())return;if(current.ticketUserAgentHash&&!equal(String(current.ticketUserAgentHash),userAgentHash))return;if(current.ticketAcceptLanguageHash&&!equal(String(current.ticketAcceptLanguageHash),acceptLanguageHash))return;current.link=next;current.completedLinks=completed;current.totalLinks=required;current.state=state;current.lastVerifiedAt=now;current.lastVerifiedHash=hash;current.lastVerifiedDeviceId=deviceId;current.verificationUsed=true;current.verificationConsumedAt=now;current.turnstileVerifiedAt=completed===required?now:null;current.ticketHash=null;current.ticketIssuedAt=null;current.ticketExpiresAt=null;current.ticketUserAgentHash=null;current.ticketAcceptLanguageHash=null;current.ticketProviderHost=null;current.externalStartedAt=null;current.verificationNonce=null;return current;});
if(!tx.committed){const latest=await ref.get(),cur=latest.exists()?(latest.val()||{}):null;if(cur&&String(cur.deviceId||'')===deviceId){const curRequired=REQUIREMENTS[Number(cur.dur)]||required;if(Number(cur.completedLinks||0)>=curRequired||Number(cur.completedLinks||0)>=link||Number(cur.link||0)>link||cur.state==='complete'){return json(res,200,{session:sessionPayload(cur),alreadyProcessed:true});}}return json(res,409,{error:'Ese paso ya fue procesado o el pase dejó de ser válido.'});}
const out=tx.snapshot.exists()?tx.snapshot.val():{};await database.ref(`sessionTickets/${ticketHash}`).update({used:true,usedAt:now,completedLinks:completed});res.setHeader('Set-Cookie','__Host-znexus_ticket=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return json(res,200,{session:sessionPayload(out)});
}catch(e){console.error('linkvertise/verify:',e);return json(res,Number(e?.status)||500,{error:e?.name==='AbortError'?'Turnstile tardó demasiado en responder.':(typeof e?.message==='string'?e.message:'Error interno del servidor.')});}};
