const crypto = require('crypto');
const admin = require('firebase-admin');
const REQUIREMENTS = { 6: 1, 12: 2, 24: 3, 30: 4 };
const KEY_RE = /^FREE_[A-Z]{9}-[0-9]{4}$/;
const DEVICE_RE = /^HWID-[A-Z0-9]{24}$/;

function json(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.end(JSON.stringify(payload));}
function parseServiceAccount(raw){let s=String(raw||'').trim();for(const candidate of [s,(s.startsWith('"')&&s.endsWith('"'))?(()=>{try{return JSON.parse(s)}catch{return s}})():null].filter(Boolean)){try{let o=JSON.parse(candidate);if(typeof o==='string')o=JSON.parse(o);if(o?.project_id&&o?.client_email&&o?.private_key){o.private_key=String(o.private_key).replace(/\\n/g,'\n');return o;}}catch{}}throw new Error('La credencial de Firebase no es válida.');}
function db(){const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSONZ||process.env.FIREBASE_SERVICE_ACCOUNT_JSON;const url=process.env.FIREBASE_DATABASE_URL;if(!raw||!url)throw new Error('Firebase del servidor no está configurado.');const app=admin.apps.length?admin.app():admin.initializeApp({credential:admin.credential.cert(parseServiceAccount(raw)),databaseURL:url});return app.database();}
function randomKey(){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ';let letters='';for(let i=0;i<9;i++)letters+=chars[crypto.randomInt(chars.length)];return `FREE_${letters}-${String(crypto.randomInt(10000)).padStart(4,'0')}`;}
async function getSession(database,id){if(!/^[a-f0-9-]{20,100}$/i.test(String(id||'')))throw Object.assign(new Error('Sesión inválida.'),{status:400});const snap=await database.ref(`sessions/${id}`).get();if(!snap.exists())throw Object.assign(new Error('Sesión no encontrada.'),{status:404});const s=snap.val()||{};if(Number(s.expiresAt)<=Date.now())throw Object.assign(new Error('La sesión expiró.'),{status:410});return s;}
module.exports=async(req,res)=>{try{if(req.method!=='POST')return json(res,405,{error:'Método no permitido.'});const data=req.body&&typeof req.body==='object'?req.body:await new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch{reject(new Error('JSON inválido.'))}});req.on('error',reject)});const sessionId=String(data.sessionId||'').trim(),deviceId=String(data.deviceId||'').trim();if(!DEVICE_RE.test(deviceId))return json(res,400,{error:'Device ID inválido.'});const database=db();const s=await getSession(database,sessionId);if(s.deviceId!==deviceId)return json(res,403,{error:'El dispositivo no coincide con la sesión.'});const total=REQUIREMENTS[Number(s.dur)];if(s.state!=='complete'||Number(s.completedLinks||0)!==total)return json(res,409,{error:'La sesión no completó todos los pasos.'});const owner=crypto.createHash('sha256').update(deviceId).digest('hex'),ownerRef=database.ref(`keyOwners/${owner}`),ownerSnap=await ownerRef.get();if(ownerSnap.exists()){const oldKey=String(ownerSnap.val()?.key||'');if(KEY_RE.test(oldKey)){const old=await database.ref(`keys/${oldKey}`).get();const k=old.val()||{};if(old.exists()&&k.status==='active'&&Number(k.expiresAt)>Date.now()&&k.hwid===deviceId){await database.ref(`sessions/${sessionId}`).remove();return json(res,200,{key:oldKey,expiresAt:Number(k.expiresAt),existing:true});}}await ownerRef.remove();}
let key=null,record=null;for(let i=0;i<12&&!key;i++){const candidate=randomKey(),createdAt=Date.now(),expiresAt=createdAt+Number(s.dur)*3600000,ref=database.ref(`keys/${candidate}`);const tx=await ref.transaction(cur=>cur||{createdAt,expiresAt,hwid:deviceId,bound:true,boundAt:createdAt,ownerHash:owner,hours_duration:Number(s.dur),sessionId,status:'active',formatVersion:2});if(tx.committed){key=candidate;record=tx.snapshot.val();}}
if(!key)return json(res,503,{error:'No se pudo reservar una key única. Inténtalo otra vez.'});await ownerRef.set({key,expiresAt:Number(record.expiresAt),updatedAt:Date.now()});await database.ref(`sessions/${sessionId}`).remove();return json(res,200,{key,expiresAt:Number(record.expiresAt),hwidBound:true});}catch(e){console.error('key/generate:',e);return json(res,e?.status||500,{error:e?.message||'Error interno del servidor.',code:e?.code||'KEY_GENERATE_FAILED'});}};